module.exports = [
  {
    title: 'Free online development tools',
    path: '/',
    page: '@pages/index',
    sitemap: true,
  },
  {
    title: 'CSS to JSS',
    path: '/css-to-jss',
    page: '@pages/css-to-jss',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'Markdown to HTML',
    path: '/markdown-to-html',
    page: '@pages/markdown-to-html',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'Markdown to React',
    path: '/markdown-to-react',
    page: '@pages/markdown-to-react',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'SQL Formatter',
    path: '/format-sql',
    page: '@pages/format-sql',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'JSON Formatter',
    path: '/format-json',
    page: '@pages/format-json',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'XML Formatter',
    path: '/format-xml',
    page: '@pages/format-xml',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'Base64 Encode',
    path: '/base64-encode',
    page: '@pages/base64-encode',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'Base64 Decode',
    path: '/base64-decode',
    page: '@pages/base64-decode',
    menus: ['tools'],
    sitemap: true,
  },
  {
    title: 'Privacy Policy',
    path: '/privacy-policy',
    page: '@pages/privacy-policy',
    menus: ['links'],
    sitemap: true,
  },
  {
    title: 'Cookie Policy',
    path: '/cookie-policy',
    page: '@pages/cookie-policy',
    menus: ['links'],
    sitemap: true,
  },
  {
    title: 'Not Found',
    path: '**',
    page: '@pages/404',
  }
];
