const languages : monacoLanguages[] = [
  // 'abap',
  // 'aes',
  // 'apex',
  // 'azcli',
  // 'bat',
  // 'bicep',
  // 'c',
  // 'cameligo',
  // 'clojure',
  // 'coffeescript',
  // 'cpp',
  // 'csharp',
  // 'csp',
  'css',
  // 'dart',
  'dockerfile',
  // 'ecl',
  // 'elixir',
  // 'flow9',
  // 'fsharp',
  // 'go',
  'graphql',
  // 'handlebars',
  // 'hcl',
  'html',
  // 'ini',
  // 'java',
  'javascript',
  'json',
  // 'julia',
  // 'kotlin',
  // 'less',
  // 'lexon',
  // 'liquid',
  // 'lua',
  // 'm3',
  'markdown',
  // 'mips',
  // 'msdax',
  'mysql',
  // 'objective-c',
  // 'pascal',
  // 'pascaligo',
  // 'perl',
  // 'pgsql',
  // 'php',
  // 'pla',
  'plaintext',
  // 'postiats',
  // 'powerquery',
  // 'powershell',
  // 'proto',
  // 'pug',
  'python',
  // 'qsharp',
  // 'r',
  // 'razor',
  // 'redis',
  // 'redshift',
  // 'restructuredtext',
  'ruby',
  // 'rust',
  // 'sb',
  // 'scala',
  // 'scheme',
  'scss',
  'shell',
  // 'sol',
  // 'sparql',
  'sql',
  // 'st',
  'swift',
  // 'systemverilog',
  // 'tcl',
  // 'twig',
  'typescript',
  // 'vb',
  // 'verilog',
  'xml',
  'yaml'
];

export const languageNameMap : Record<monacoLanguages, string> = {
  css: 'CSS',
  dockerfile: 'Dockerfile',
  graphql: 'GraphQL',
  html: 'HTML',
  javascript: 'JavaScript',
  json: 'JSON',
  markdown: 'Markdown',
  mysql: 'MySQL',
  ruby: 'Ruby',
  scss: 'Sass',
  shell: 'Shell',
  sql: 'SQL',
  swift: 'Swift',
  typescript: 'TypeScript',
  plaintext: 'Plantext',
  python: 'Python',
  xml: 'XML',
  yaml: 'Yaml',
};

export default languages;